# MadLibs

print("Welcome to the Mad Libs")
print("Please choose a template:")

choice = input("Enter 1, 2, or 3: ")

if choice == "1":
    number1 = input("Enter a number: ")
    measure_time = input("Enter a measure of time: ")
    transport = input("Enter a mode of transportation: ")
    adj1 = input("Enter an adjective: ")
    adj2 = input("Enter another adjective: ")
    noun1 = input("Enter a noun: ")
    color = input("Enter a color: ")
    body_part = input("Enter a part of the body: ")
    verb1 = input("Enter a verb: ")
    number2 = input("Enter another number: ")
    noun2 = input("Enter another noun: ")
    noun3 = input("Enter a third noun: ")
    body_part2 = input("Enter another part of the body: ")
    verb2 = input("Enter another verb: ")
    noun4 = input("Enter a fourth noun: ")
    adj3 = input("Enter a third adjective: ")
    silly_word = input("Enter a silly word: ")
    noun5 = input("Enter one last noun: ")

    print("It was about " + number1 + " " + measure_time + " ago when I arrived at the hospital in a " + transport + ".")
    print("The hospital is a/an " + adj1 + " place, there are a lot of " + adj2 + " " + noun1 + " here.")
    print("There are nurses here who have " + color + " " + body_part + ".")
    print("If someone wants to come into my room I told them that they have to " + verb1 + " first.")
    print("I've decorated my room with " + number2 + " " + noun2 + ".")
    print("Today I talked to a doctor and they were wearing a " + noun3 + " on their " + body_part2 + ".")
    print("I heard that all doctors " + verb2 + " " + noun4 + " every day for breakfast.")
    print("The most " + adj3 + " thing about being in the hospital is the " + silly_word + " " + noun5 + "!")

elif choice == "2":
    name = input("Enter a person's name: ")
    noun1 = input("Enter a noun: ")
    adj1 = input("Enter an adjective (feeling): ")
    verb1 = input("Enter a verb: ")
    adj2 = input("Enter another adjective (feeling): ")
    animal1 = input("Enter an animal: ")
    verb2 = input("Enter another verb: ")
    color1 = input("Enter a color: ")
    verb_ing = input("Enter a verb ending in 'ing': ")
    adverb = input("Enter an adverb (ending in 'ly'): ")
    number1 = input("Enter a number: ")
    measure_time = input("Enter a measure of time: ")
    color2 = input("Enter another color: ")
    animal2 = input("Enter another animal: ")
    number2 = input("Enter another number: ")
    silly_word = input("Enter a silly word: ")
    noun2 = input("Enter another noun: ")

    print("This weekend I am going camping with " + name + ". I packed my lantern, sleeping bag, and " + noun1 + ".")
    print("I am so " + adj1 + " to " + verb1 + " in a tent. I am " + adj2 + " we might see a(n) " + animal1 + ".")
    print("While we're camping, we are going to hike, fish, and " + verb2 + ".")
    print("I have heard that the " + color1 + " lake is great for " + verb_ing + ".")
    print("Then we will " + adverb + " hike through the forest for " + number1 + " " + measure_time + ".")
    print("If I see a " + color2 + " " + animal2 + " while hiking, I am going to bring it home as a pet!")
    print("At night we will tell " + number2 + " " + silly_word + " stories and roast " + noun2 + " around the campfire!!")

elif choice == "3":
    name = input("Enter a person's name: ")
    adj1 = input("Enter an adjective: ")
    color = input("Enter a color: ")
    animal = input("Enter an animal: ")
    place = input("Enter a place: ")
    adj2 = input("Enter an adjective: ")
    creature1 = input("Enter a magical creature (plural): ")
    adj3 = input("Enter another adjective: ")
    creature2 = input("Enter another magical creature (plural): ")
    room = input("Enter a room in a house: ")
    noun1 = input("Enter a noun: ")
    noun2 = input("Enter another noun: ")
    noun3 = input("Enter a noun (plural): ")
    adj4 = input("Enter another adjective: ")
    noun4 = input("Enter another noun (plural): ")
    number = input("Enter a number: ")
    measure_time = input("Enter a measure of time: ")
    verb_ing = input("Enter a verb ending in 'ing': ")
    adj5 = input("Enter one last adjective: ")
    noun5 = input("Enter one last noun: ")

    print("Dear " + name + ", I am writing to you from a " + adj1 + " castle in an enchanted forest.")
    print("I found myself here one day after going for a ride on a " + color + " " + animal + " in " + place + ".")
    print("There are " + adj2 + " " + creature1 + " and " + adj3 + " " + creature2 + " here!")
    print("In the " + room + " there is a pool full of " + noun1 + ".")
    print("I fall asleep each night on a " + noun2 + " of " + noun3 + " and dream of " + adj4 + " " + noun4 + ".")
    print("It feels as though I have lived here for " + number + " " + measure_time + ".")
    print("I hope one day you can visit, although the only way to get here now is " + verb_ing + " on a " + adj5 + " " + noun5 + "!!")

else:
    print("Invalid choice. Please pick 1, 2, or 3.")